// Code generated by "stringer --type Device"; DO NOT EDIT.

package vid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChromeCast-1]
	_ = x[ChromeCastUltra-2]
	_ = x[ChromeOS-3]
	_ = x[WEBPWebPreview-4]
}

const _Device_name = "ChromeCastChromeCastUltraChromeOSWEBPWebPreview"

var _Device_index = [...]uint8{0, 10, 25, 33, 47}

func (i Device) String() string {
	i -= 1
	if i < 0 || i >= Device(len(_Device_index)-1) {
		return "Device(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Device_name[_Device_index[i]:_Device_index[i+1]]
}
